# Generated by Django 4.2.6 on 2023-12-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
        migrations.CreateModel(
            name='BlanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'BlanceType',
                'verbose_name_plural': 'BlanceTypes',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object_id')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type')),
                ('link_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almalik.chat', verbose_name='link_chat')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'Management',
                'verbose_name_plural': 'Managements',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العرض')),
                ('file', models.FileField(blank=True, null=True, upload_to='almalik/offers/', verbose_name='file')),
                ('path', models.FilePathField(allow_folders=True, blank=True, null=True, path='F:\\almalik2\\media\\offers', verbose_name='path')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المشروع')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='اقل سعر')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='أعلى سعر')),
                ('days', models.SmallIntegerField(verbose_name='المدة')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('statu', models.CharField(choices=[('مراجعة', 'مراجعة'), ('عرض', 'عرض'), ('جاري', 'جاري'), ('تم', 'تم'), ('معلق', 'معلق'), ('ملغي', 'ملغي'), ('مرفوض', 'مرفوض')], default='مراجعة', max_length=50, verbose_name='حالة المشروع')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.department', verbose_name='نوع المشروع')),
                ('to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_to_project', to='almalik.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.offer', verbose_name='offer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'ProjectOffer',
                'verbose_name_plural': 'ProjectOffers',
            },
        ),
        migrations.CreateModel(
            name='ReceiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('account', models.CharField(max_length=50, verbose_name='account')),
            ],
            options={
                'verbose_name': 'ReceiveType',
                'verbose_name_plural': 'ReceiveTypes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_usercontact_contact', to='almalik.user', verbose_name='contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_usercontact_user', to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'UserContact',
                'verbose_name_plural': 'UserContacts',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_theme', models.CharField(choices=[('dark', 'dark'), ('ligth', 'ligth')], default='dark', max_length=50, verbose_name='choose_theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectUnAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('detail', models.TextField(verbose_name='detail')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'ProjectUnAccepted',
                'verbose_name_plural': 'ProjectUnAccepteds',
            },
        ),
        migrations.CreateModel(
            name='ProjectStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('detail', models.TextField(verbose_name='detail')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'ProjectStop',
                'verbose_name_plural': 'ProjectStops',
            },
        ),
        migrations.CreateModel(
            name='ProjectStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('period', models.SmallIntegerField(verbose_name='period')),
                ('path', models.FilePathField(allow_folders=True, blank=True, null=True, path='F:\\almalik2\\media\\projects', verbose_name='path')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
                ('projectoffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.projectoffer', verbose_name='projectoffer')),
            ],
            options={
                'verbose_name': 'ProjectStart',
                'verbose_name_plural': 'ProjectStarts',
            },
        ),
        migrations.CreateModel(
            name='ProjectJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.job', verbose_name='job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
                ('projectstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.projectstart', verbose_name='projectstart')),
            ],
            options={
                'verbose_name': 'ProjectJob',
                'verbose_name_plural': 'ProjectJobs',
            },
        ),
        migrations.CreateModel(
            name='ProjectEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('file', models.FileField(upload_to='media/projects', verbose_name='file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
                ('projectstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.projectstart', verbose_name='projectstart')),
            ],
            options={
                'verbose_name': 'ProjectEnd',
                'verbose_name_plural': 'ProjectEnds',
            },
        ),
        migrations.CreateModel(
            name='ProjectDdownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
                ('projectend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.projectend', verbose_name='projectend')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ProjectDdownload',
                'verbose_name_plural': 'ProjectDdownloads',
            },
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('period_days', models.IntegerField(verbose_name='period_days')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('detail', models.TextField(verbose_name='detail')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
                ('projectend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.projectend', verbose_name='projectend')),
            ],
            options={
                'verbose_name': 'ProjectCode',
                'verbose_name_plural': 'ProjectCodes',
            },
        ),
        migrations.CreateModel(
            name='ProjectApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'ProjectApp',
                'verbose_name_plural': 'ProjectApps',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datebirth', models.DateField(blank=True, null=True, verbose_name='datebirth')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='profession')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='OfferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('period', models.SmallIntegerField(verbose_name='period')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.job', verbose_name='job')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.offer', verbose_name='offer')),
            ],
            options={
                'verbose_name': 'OfferJob',
                'verbose_name_plural': 'OfferJobs',
            },
        ),
        migrations.CreateModel(
            name='NoticeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=False, verbose_name='is_view')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.notice', verbose_name='notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'NoticeUser',
                'verbose_name_plural': 'NoticeUsers',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/', verbose_name='image')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/file/', verbose_name='file')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type')),
            ],
            options={
                'verbose_name': 'ملف',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.management', verbose_name='management'),
        ),
        migrations.CreateModel(
            name='ChatVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='account/chat/videos', verbose_name='video')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.chat', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'ChatVideo',
                'verbose_name_plural': 'ChatVideos',
            },
        ),
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='account/chat/images', verbose_name='image')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.chat', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'ChatImage',
                'verbose_name_plural': 'ChatImages',
            },
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='account/chat/file', verbose_name='file')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.chat', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'ChatFile',
                'verbose_name_plural': 'ChatFiles',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_chat_to_user', to='almalik.user', verbose_name='to_user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='BalanceSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('statu', models.CharField(choices=[('1', 'مراجعة'), ('0', 'ملغي')], default='1', max_length=50, verbose_name='statu')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.balance', verbose_name='balance')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'BalanceSpend',
                'verbose_name_plural': 'BalanceSpends',
            },
        ),
        migrations.CreateModel(
            name='BalanceReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='datetime_add')),
                ('datetime_change', models.DateTimeField(auto_now=True, verbose_name='datetime_change')),
                ('number', models.BigIntegerField(verbose_name='number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('statu', models.CharField(choices=[('1', 'مراجعة'), ('OK', 'تم'), ('0', 'ملغي')], default='1', max_length=50, verbose_name='statu')),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almalik.balance', verbose_name='balance')),
                ('receive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.receivetype', verbose_name='receive_type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'BalanceReceive',
                'verbose_name_plural': 'BalanceReceives',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='balance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.blancetype', verbose_name='balance_type'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almalik.user', verbose_name='المستخدم'),
        ),
    ]
