# Generated by Django 4.2.6 on 2023-12-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almalik', '0002_alter_balance_user_alter_balancereceive_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeuser',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='is_notice'),
        ),
    ]
